

#define TEXT_1 "Carol y Cristobal fueron a Acampar a Rio Azul en un lindo día de verano...\CRISTOBAL:\nLinda, Te tinca si mientras armo la carpa preparas desayuno?\nCAROL:\nBueno, me tinca :)\nPresiona SET para cambiar de personaje"
#define TEXT_2 "CAROL:\nNecesito el Sarten, ¿donde estara?"
#define TEXT_4 "CRISTOBAL:\nNecesito las estacas, ¿donde estaran?"
#define TEXT_6 "CAROL:\nAqui estaba el sarten, preparare el desayuno en la fogata"
#define TEXT_7 "CAROL:\nhace falta fosforos para prender el fuego"
#define TEXT_8 "CAROL:\nMe dan miedo los perros, me pueden morder :C\nCACHUPIN: Guau, Guau.\nCAROL:\nquizas el Cristobal podra espantarlos"
#define TEXT_9 "CRISTOBAL:\nCHU-CHU, Perrito\nCACHUPIN: Guau, Guau."
#define TEXT_10 "CAROL:\n¿Tendra fosforos que nos venda?\nVECINA:\nSi, aqui tiene!\nCAROL:\nMuchisimas gracias"
#define TEXT_11 "CAROL:\nEsta Listo el desayuno"
#define TEXT_12 "CRISTOBAL:\nMe es dificil hablar con extranos, la carol tiene habilidad para eso"
#define TEXT_15 "CAROL:\nEl agua esta muy helada, necesito mis calcetines,  ¿donde estaran?"
#define TEXT_16 "CRISTOBAL:\nMe pondré mi traje de baño para cruzar el rio, ¿donde estara?"
#define TEXT_17 "CRISTOBAL:\nNecesito una botella de agua para el camino"
#define TEXT_18 "CAROL:\nEl camino se ve malo, necesito mis zapatillas de trekking"
#define TEXT_19 "CAROL:\nCreo que gustaria una foto aqui, donde estará la tablet"
#define TEXT_20 "CAROL:\n¿Nos podria sacar una foto?"
#define TEXT_21 "CAROL:\nTe tengo una sorpresa Cristobal, te escondi un huevito de chocolate, crees que puedas encontrarlo?\nCRISTOBAL: En Serio amor?, hare mi mejor esfuerzo"
#define TEXT_22 "CAROL:\nFrio Frio..."
#define TEXT_23 "CAROL:\nCaliente Caliente..."
#define TEXT_24 "Carol y Cristóbal tuvieron unas excelentes vacaciones. Hasta la próxima aventura :)"
#define TEXT_25 "CRISTOBAL:\nNo encuentro mis llaves, ¿donde estara?"
#define TEXT_26 "CAROL:\nEl Cristobal me ensenara a manejar, pero por hoy creo que el debe mover el auto"
#define TEXT_27 "AUTO:\nBroom brooom\nCRISTOBAL: Amor vamos ya a la cascada?"
#define TEXT_28 "CRISTOBAL:\nAqui estan las estacas! Buscare un buen lugar para armar la carpa cerca del fuego."
#define TEXT_29 "CAROL:\nEsta fogata esta ideal para preparar desayuno"
#define TEXT_30 "CRISTOBAL:\nLa carpa debe ir cerca de la fogata"
#define TEXT_31 "CACHUPIN: Guau, Guau"
#define TEXT_32 "CRISTOBAL:\nEstaba muy rico el desayuno y creo que quedo muy bien la carpa\nCAROL:\nGracias amor, podrías acercar el auto a la carpa para poder tener a mano las cosas."
#define TEXT_33 "CRISTOBAL:\nCon el fuego encendido podre saber mejor donde poner la carpa"
#define TEXT_34 "/2 Calcetines"
#define TEXT_35 "CRISTOBAL:\nAqui estaba mi short"
#define TEXT_36 "CRISTOBAL:\nAqui estaba mi llave"
#define TEXT_37 "CRISTOBAL:\nYa llene la botella"
#define TEXT_38 "/2 Zapatillas"