

#define TEXT_1 "Capitulo I: La foto perfecta\nCarol y Cristobal llegaron a un hermoso camping en una bella y despejada jornada...\nCRISTOBAL:\nLinda, Te tinca si mientras armo la carpa preparas desayuno?\nCAROL:\nSii, tengo ganas de probar los huevitos que compramos"
#define TEXT_2 "\nCAROL:\nNecesito el Sarten, donde estara?"
#define TEXT_3 "\nCRISTOBAL:\nNecesito las estacas, donde estaran?"
#define TEXT_6 "CAROL:\nAqui estaba el sarten, preparare el desayuno en la fogata"
#define TEXT_7 "CAROL:\nhace falta fosforos para prender el fuego"
#define TEXT_8 "CAROL:\nMe dan miedo los perros, me pueden morder :C\nCACHUPIN: Guau, Guau.\nCAROL:\nquizas el Cristobal podra espantarlos\nPresiona SET para cambiar de personaje"
#define TEXT_9 "CRISTOBAL:\nCHU-CHU, Perrito\nCACHUPIN: Guau, Guau."
#define TEXT_10 "CAROL:\n¿Tendra fosforos que nos venda?\nVECINA:\nSi, aqui tiene!\nCAROL:\nMuchisimas gracias"
#define TEXT_11 "CAROL:\nEsta Listo el desayuno!\nEsta lista la carpa?\nCRISTOBAL:\nCasi casi, necesito las estacas, ¿donde estaran?"
#define TEXT_12 "CRISTOBAL:\nMe es dificil hablar con extranos, para esto, la Carol es muy habilidadosa"
#define TEXT_15 "CAROL:\nEl agua esta muy helada, necesito mis calcetines,  ¿donde estaran?"
#define TEXT_16 "CRISTOBAL:\nMe pondre mi traje de bano para cruzar el rio, ¿donde estara?"
#define TEXT_17 "CRISTOBAL:\nNecesito una botella de agua para el camino"
#define TEXT_18 "CAROL:\nEl camino se ve malo, necesito mis zapatillas de trekking"
#define TEXT_20 "CAROL:\n¿Nos podria sacar una foto en la cascada?\nTURISTA:\nClaro tienes con que tomarla?\nCAROL:\nmmm, habria que buscar la tablet del cristobal\nTURISTA:\nCuando tengas la tablet, vuelve y les tomo una foto :)"
#define TEXT_25 "CRISTOBAL:\nNo encuentro mis llaves, ¿donde estaran?"
#define TEXT_26 "CAROL:\nEl Cristobal me ensenara a manejar, pero por hoy creo que el debe mover el auto"
#define TEXT_27 "AUTO:\nBroom brooom\nCRISTOBAL: Listo linda, vamos a la cascada?\nCAROL:\nSi tengo muchas ganas :)"
#define TEXT_28 "CRISTOBAL:\nAqui estan las estacas! Buscare un buen lugar para armar la carpa cerca del fuego."
#define TEXT_29 "CAROL:\nEsta fogata esta ideal para preparar desayuno\nsolo me hace falta el sarten, donde estara?"
#define TEXT_30 "CRISTOBAL:\nLa carpa debe ir cerca de la fogata"
#define TEXT_31 "CACHUPIN: Guau, Guau"
#define TEXT_32 "CRISTOBAL:\nEstaba muy rico el desayuno y creo que quedo muy bien la carpa\nCAROL:\nGracias amor, podrias acercar el auto a la carpa para poder tener a mano las cosas.\nCRISTOBAL:\nObvio que si ;)"
#define TEXT_33 "CRISTOBAL:\nSi el fuego estuviese encendido tendria una mejor nocion de donde poner la carpa"
#define TEXT_34 "/2 Calcetines"
#define TEXT_35 "CRISTOBAL:\nAqui estaba mi short"
#define TEXT_36 "CRISTOBAL:\nAqui estaba mi llave"
#define TEXT_37 "CRISTOBAL:\nYa llene la botella"
#define TEXT_38 "/2 Zapatillas"
#define TEXT_39 "CRISTOBAL:\nAqui estaba mi Tablet"
#define TEXT_40 "CAROL:\nLa encontramos ;) ahora si?\nTURISTA:\nPor su puesto!"
#define TEXT_41 "CAROL:\nEsperare que el Cristobal este listo"
#define TEXT_42 "CRISTOBAL:\nEsperare que la Carol este lista"
#define TEXT_43 "Capitulo II:\nUna sorpresa encantadora\nYa es hora para nuestros protagonistas de volver a la carpa y disfrutar el atardecer...\nCRISTOBAL:Me gustaria buscar un honguito como recuerdo\nCAROL:\ncruzando el rio quizas encontraremos alguno."
#define TEXT_44 "Cristobal:\n Mira amor, encontre un lindo honguito.\nCarol:\nHermoso, mientras tu buscabas, escondi unos huevitos de chocolate para ti, podras encontrarlos todos?\nCRISTOBAL:\nD: En serio?, Hare mi mayor esfuerzo"
#define TEXT_45 "/10 Huevitos"
#define TEXT_46 "CRISTOBAL:\nLos huevitos estuvieron deliciosos y me encanto la sorpresa  :)\nCAROL:\nNo hay de que, Ahora me ensenas a tocar guitarra amor?"
#define TEXT_47 "CAROL y CRISTOBAL:\nHojas de te, amanecer, y un dia mas...\nCarol y Cristobal terminaron su aventura, hasta la proxima :)"
#define TEXT_48 "Un letrero viejo que indica un sendero antiguo"
